### ISSUE TITLE
Secure website entry redirects to Ryan's blog

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/Freetime-www#11]
https://githawk.com/ shows https://whoisryannystrom.com/

🤔

**Comment by rnystrom** [comment]
Can we move to the website repo?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
Sorry I'm not following @rnystrom, is there another repo for the website that I don't know of?

**Comment by rnystrom** [comment]
Oh lol I’m dumb thought this was in the app

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
All good haha! Minor issue anyway we just slightly confused when I went on secure and wasn't seeing the site!

**Comment by ghecho** [comment]
Are you using GitHub pages? I think that it may be the best way to host this and you'll get the TLS certificate managed for free (reference from #12 ). 

See [this (GitHub pages setup)](https://help.github.com/articles/using-a-custom-domain-with-github-pages/) and [this (for enforcing TLS)](https://help.github.com/articles/securing-your-github-pages-site-with-https/).

**Comment by tigpt** [comment]
Site is in it's own domain and with a Let's Encrypt certificate.

Ready to be closed.
