### ISSUE TITLE
Ideas to solve the https.

### ISSUE THREAD

**Issue by dantehemerson** [rnystrom/Freetime-www#12]
I noticed that your website is not secure, I think you should solve that. I have a couple of ideas:
If you do not yet have an SSL certificate you could generate it for free in  [Letsencrypt](https://letsencrypt.org/).
Or you can pass the site to [Netlify](https://www.netlify.com/), it allows you to set up your own domain and you have the option to configure free https automatically through  [Letsencrypt](https://letsencrypt.org/). This also would resolves the previous issue #11.

**Comment by rnystrom** [comment]
Yup known problem, easy to solve? Just need to remember. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Closing since a dupe of #11

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
